# Generated by Django 5.1.2 on 2024-11-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rachunki',
            name='laczna_cena',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sprzedaze',
            name='laczna_cena',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='towary',
            name='cena_bez_vat',
            field=models.FloatField(),
        ),
    ]
