# Generated by Django 5.1.2 on 2024-11-07 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0002_alter_rachunki_laczna_cena_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('products_count', models.IntegerField()),
                ('price_no_vat', models.FloatField()),
                ('price_with_vat', models.FloatField()),
            ],
            options={
                'db_table': 'bills',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rank', models.IntegerField()),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('unit', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('price_no_vat', models.FloatField()),
                ('vat', models.IntegerField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.RemoveField(
            model_name='faktury',
            name='id_rachunku',
        ),
        migrations.RemoveField(
            model_name='sprzedaze',
            name='id_rachunku',
        ),
        migrations.RemoveField(
            model_name='sprzedaze',
            name='id_towaru',
        ),
        migrations.RemoveField(
            model_name='usuniecia',
            name='id_towaru',
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('nip_number', models.IntegerField()),
                ('buyer_name', models.CharField(max_length=50)),
                ('bill_id', models.ForeignKey(db_column='bill_id', on_delete=django.db.models.deletion.DO_NOTHING, to='shop1.bill')),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='Deletion',
            fields=[
                ('deletion_id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('deletion_date', models.DateField()),
                ('product_id', models.ForeignKey(db_column='id_towaru', on_delete=django.db.models.deletion.DO_NOTHING, to='shop1.product')),
            ],
            options={
                'db_table': 'deletions',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('price_no_vat', models.FloatField()),
                ('price_with_vat', models.FloatField()),
                ('bill_id', models.ForeignKey(db_column='bill_id', on_delete=django.db.models.deletion.DO_NOTHING, to='shop1.bill')),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, to='shop1.product')),
            ],
            options={
                'db_table': 'sales',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('supply_id', models.AutoField(primary_key=True, serialize=False)),
                ('supply_date', models.DateField()),
                ('count', models.IntegerField()),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, to='shop1.product')),
            ],
            options={
                'db_table': 'supplies',
            },
        ),
        migrations.DeleteModel(
            name='Dostawy',
        ),
        migrations.DeleteModel(
            name='Faktury',
        ),
        migrations.DeleteModel(
            name='Rachunki',
        ),
        migrations.DeleteModel(
            name='Sprzedaze',
        ),
        migrations.DeleteModel(
            name='Towary',
        ),
        migrations.DeleteModel(
            name='Usuniecia',
        ),
    ]
