# Generated by Django 5.1.2 on 2024-11-07 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1', '0003_bill_employee_product_remove_faktury_id_rachunku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='rank',
        ),
        migrations.AddField(
            model_name='bill',
            name='employee_id',
            field=models.ForeignKey(db_column='employee_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='shop1.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deletion',
            name='employee_id',
            field=models.ForeignKey(db_column='employee_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='shop1.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='price_with_vat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supply',
            name='employee_id',
            field=models.ForeignKey(db_column='employee_id', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='shop1.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deletion',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.DO_NOTHING, to='shop1.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat',
            field=models.IntegerField(choices=[(0, 'Zero'), (5, 'Five'), (8, 'Eight'), (23, 'Twenty Three')]),
        ),
    ]
